# Generated by Django 5.2.4 on 2025-07-30 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('rating', models.CharField(choices=[('Excellent', 'Excellent (850-900)'), ('Very Good', 'Very Good (750-849)'), ('Good', 'Good (650-749)'), ('Fair', 'Fair (550-649)'), ('Poor', 'Poor (300-549)')], max_length=20)),
                ('base_score', models.IntegerField(default=500)),
                ('transaction_frequency_points', models.IntegerField(default=0)),
                ('average_balance_points', models.IntegerField(default=0)),
                ('income_regularity_points', models.IntegerField(default=0)),
                ('payment_history_points', models.IntegerField(default=0)),
                ('overdraft_penalty', models.IntegerField(default=0)),
                ('factors', models.JSONField(default=dict)),
                ('improvement_tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_frequency', models.IntegerField(default=0)),
                ('overdraft_count', models.IntegerField(default=0)),
                ('payment_history_score', models.IntegerField(default=0)),
                ('income_consistency', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
