# Generated by Django 5.2.4 on 2025-07-30 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creditscore_financialdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('is_linked', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MPesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('business', 'Business Income'), ('bills', 'Bills Payment'), ('shopping', 'Shopping'), ('transport', 'Transport'), ('food', 'Food & Dining'), ('utilities', 'Utilities'), ('transfer', 'Money Transfer'), ('withdraw', 'Cash Withdrawal'), ('airtime', 'Airtime Purchase'), ('loan', 'Loan Payment'), ('savings', 'Savings'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mpesa_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.mpesaaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
