# Generated by Django 5.2.4 on 2025-07-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mpesaaccount_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='ai_insights',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated insights and analysis'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='ai_processed',
            field=models.BooleanField(default=False, help_text='Whether transaction was processed with AI'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='original_sms',
            field=models.TextField(blank=True, help_text='Original SMS message', null=True),
        ),
    ]
